-- AlterTable
ALTER TABLE "Config" ADD COLUMN "botMode" TEXT NOT NULL DEFAULT 'hybrid';
ALTER TABLE "Config" ADD COLUMN "mmMinVolume24h" INTEGER NOT NULL DEFAULT 15000;
ALTER TABLE "Config" ADD COLUMN "mmMaxSpread" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "Config" ADD COLUMN "mmBaseSpreadCents" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Config" ADD COLUMN "mmOrderSize" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Config" ADD COLUMN "mmMaxMarkets" INTEGER NOT NULL DEFAULT 3;
