-- AlterTable
ALTER TABLE "DailyStats" ADD COLUMN     "currentPnl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "feesPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "maxDrawdown" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ordersCanceled" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ordersPlaced" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "peakPnl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "startingBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tradesCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ParityTrade" ADD COLUMN     "actualFees" DOUBLE PRECISION,
ADD COLUMN     "estimatedFees" DOUBLE PRECISION;
